import Foundation
import MLX
import Testing

@testable import ProtenixMLX

/// Replays fixtures recorded from upstream PyTorch and asserts the Swift port agrees.
///
/// Fixtures are generated by `protenix-mlx make-fixtures` into `.artifacts/fixtures`
/// and are not committed -- they are a few megabytes of random weights, reproducible
/// from a seed. When they are absent these tests SKIP rather than pass, so a missing
/// fixture tree can never be mistaken for a verified port.
struct Fixture {
  let name: String
  let tensors: [String: MLXArray]
  let config: [String: Any]

  static var root: URL? {
    // Walk up from this file to the package root, which is where .artifacts lives.
    var directory = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent()  // ProtenixMLXTests
      .deletingLastPathComponent()  // tests
      .deletingLastPathComponent()  // package root
    directory = directory.appending(path: ".artifacts/fixtures")
    return FileManager.default.fileExists(atPath: directory.path) ? directory : nil
  }

  static func load(_ name: String) throws -> Fixture? {
    guard let root else { return nil }
    let directory = root.appending(path: name)
    guard FileManager.default.fileExists(atPath: directory.path) else { return nil }
    let tensors = try MLX.loadArrays(
      url: directory.appending(path: "tensors.safetensors"))
    let data = try Data(contentsOf: directory.appending(path: "case.json"))
    let decoded =
      (try JSONSerialization.jsonObject(with: data) as? [String: Any]) ?? [:]
    return Fixture(
      name: name,
      tensors: tensors,
      config: (decoded["config"] as? [String: Any]) ?? [:]
    )
  }

  /// Build a `WeightStore` over this fixture's `weight.*` arrays, rooted at `path`.
  ///
  /// The fixture's weights are dense float32, so this exercises the same dense branch
  /// a float16/bfloat16 pack takes. Quantized packs are covered separately by the
  /// int8-vs-dense equivalence test.
  func store(rootedAt path: String) throws -> WeightStore {
    var arrays: [String: MLXArray] = [:]
    var specs: [TensorSpec] = []
    for (key, value) in tensors where key.hasPrefix("weight.") {
      let name = path.isEmpty
        ? String(key.dropFirst("weight.".count))
        : "\(path).\(key.dropFirst("weight.".count))"
      arrays[name] = value
      specs.append(
        TensorSpec(
          name: name, shape: value.shape, dtype: ArtifactIO.dtypeName(value.dtype),
          shard: "model.safetensors", logicalShape: nil, physicalShape: nil))
    }
    let manifest = ArtifactManifest(
      schemaVersion: 1, artifactKind: .model, modelName: "fixture",
      sourceRevision: "fixture", sourceCommit: String(repeating: "0", count: 40),
      sourceCheckpointSha256: nil,
      tensors: specs.sorted { $0.name < $1.name }, quantization: nil)
    return WeightStore(
      artifact: ProtenixArtifact(
        manifest: manifest,
        configuration: try Self.placeholderConfiguration(),
        arrays: arrays))
  }

  func input(_ name: String) -> MLXArray { tensors["input.\(name)"]! }
  var expected: MLXArray { tensors["output"]! }
  func integer(_ key: String) -> Int { (config[key] as? Int) ?? 0 }
  func flag(_ key: String) -> Bool { (config[key] as? Bool) ?? false }

  private static func placeholderConfiguration() throws -> ProtenixModelConfiguration {
    let json = """
      {"schema_version":1,"model_name":"fixture","source_revision":"f",
       "source_commit":"0","c_s":1,"c_z":1,"c_s_inputs":1,"c_atom":1,
       "c_atompair":1,"c_token":1,"n_cycle":1,"n_diffusion_steps":1,
       "parameter_count":0,"quantized_matrix_count":0,"graph_roots":[],
       "model":{"pairformer":{"n_blocks":0,"n_heads":1,"c_s":1,"c_z":1,
         "hidden_scale_up":false},
        "msa_module":{"n_blocks":0,"c_m":1,"c_z":1,"c_s_inputs":1,
         "hidden_scale_up":false,"msa_max_size":1},
        "template_embedder":{"n_blocks":0,"c":1,"c_z":1,"hidden_scale_up":false},
        "confidence_head":{"n_blocks":0,"c_s":1,"c_z":1,"c_s_inputs":1,
         "max_atoms_per_token":1,"distance_bin_start":0,"distance_bin_end":1,
         "distance_bin_step":1,"hidden_scale_up":false},
        "diffusion_module":{"c_atom":1,"c_atompair":1,"c_token":1,"c_s":1,"c_z":1,
         "c_s_inputs":1,"sigma_data":1,"atom_encoder":{"n_blocks":0,"n_heads":1},
         "atom_decoder":{"n_blocks":0,"n_heads":1},
         "transformer":{"n_blocks":0,"n_heads":1}},
        "distogram_head":{"c_z":1,"no_bins":1},
        "input_embedder":{"c_atom":1,"c_atompair":1,"c_token":1},
        "relative_position_encoding":{"c_z":1,"r_max":1,"s_max":1}}}
      """
    return try JSONDecoder().decode(
      ProtenixModelConfiguration.self, from: Data(json.utf8))
  }
}

/// Largest relative deviation from the reference, scaled by the reference's own range.
private func maximumDeviation(_ value: MLXArray, _ reference: MLXArray) -> Float {
  let a = value.asType(.float32)
  let b = reference.asType(.float32)
  let scale = max(MLX.abs(b).max().item(Float.self), 1e-6)
  return MLX.abs(a - b).max().item(Float.self) / scale
}

/// float32 fixtures against float32 Swift arithmetic: the only differences should be
/// reassociation in the matmuls, which lands several orders below this.
private let tolerance: Float = 2e-4

@Suite("PyTorch parity")
struct ParityTests {

  private func fixture(_ name: String) throws -> Fixture? {
    let loaded = try Fixture.load(name)
    if loaded == nil {
      // Visible in the log rather than silently green.
      print("SKIP \(name): no fixture at .artifacts/fixtures (run make-fixtures)")
    }
    return loaded
  }

  @Test("transition matches upstream")
  func transition() throws {
    guard let fixture = try fixture("transition") else { return }
    let layer = try Transition(
      store: fixture.store(rootedAt: "m"), path: "m")
    let output = layer(fixture.input("x"))
    #expect(output.shape == fixture.expected.shape)
    #expect(maximumDeviation(output, fixture.expected) < tolerance)
  }

  @Test("adaptive layer norm matches upstream")
  func adaptiveLayerNorm() throws {
    guard let fixture = try fixture("adaptive_layernorm") else { return }
    let layer = try AdaptiveLayerNorm(
      store: fixture.store(rootedAt: "m"), path: "m")
    let output = layer(fixture.input("a"), fixture.input("s"))
    #expect(maximumDeviation(output, fixture.expected) < tolerance)
  }

  @Test("attention pair bias with single conditioning matches upstream")
  func attentionPairBiasWithS() throws {
    guard let fixture = try fixture("attention_pair_bias_with_s") else { return }
    let store = try fixture.store(rootedAt: "m")
    let layer = try AttentionPairBias(
      store: store, path: "m", headCount: fixture.integer("n_heads"))
    #expect(layer.hasS)
    let output = layer(
      fixture.input("a"), s: fixture.input("s"), z: fixture.input("z"))
    #expect(output.shape == fixture.expected.shape)
    #expect(maximumDeviation(output, fixture.expected) < tolerance)
  }

  @Test("attention pair bias without conditioning matches upstream")
  func attentionPairBiasNoS() throws {
    guard let fixture = try fixture("attention_pair_bias_no_s") else { return }
    let store = try fixture.store(rootedAt: "m")
    let layer = try AttentionPairBias(
      store: store, path: "m", headCount: fixture.integer("n_heads"))
    // The no-s configuration must be detected from the weights, not assumed: it drops
    // the output gate entirely.
    #expect(layer.hasS == false)
    let output = layer(fixture.input("a"), s: nil, z: fixture.input("z"))
    #expect(maximumDeviation(output, fixture.expected) < tolerance)
  }

  @Test(
    "triangle multiplication matches upstream",
    arguments: [
      ("triangle_multiplication_outgoing", true),
      ("triangle_multiplication_incoming", false),
    ])
  func triangleMultiplication(name: String, outgoing: Bool) throws {
    guard let fixture = try fixture(name) else { return }
    let layer = try TriangleMultiplication(
      store: fixture.store(rootedAt: "m"), path: "m", outgoing: outgoing)
    let output = layer(fixture.input("x"))
    #expect(output.shape == fixture.expected.shape)
    #expect(maximumDeviation(output, fixture.expected) < tolerance)
  }

  @Test(
    "triangle attention matches upstream",
    arguments: [
      ("triangle_attention_starting", true),
      ("triangle_attention_ending", false),
    ])
  func triangleAttention(name: String, starting: Bool) throws {
    guard let fixture = try fixture(name) else { return }
    let layer = try TriangleAttention(
      store: fixture.store(rootedAt: "m"), path: "m", starting: starting,
      headCount: fixture.integer("n_heads"))
    let output = layer(fixture.input("x"))
    #expect(output.shape == fixture.expected.shape)
    #expect(maximumDeviation(output, fixture.expected) < tolerance)
  }

  @Test("outer product mean matches upstream")
  func outerProductMean() throws {
    guard let fixture = try fixture("outer_product_mean") else { return }
    let layer = try OuterProductMean(
      store: fixture.store(rootedAt: "m"), path: "m")
    let output = layer(fixture.input("m"))
    #expect(output.shape == fixture.expected.shape)
    #expect(maximumDeviation(output, fixture.expected) < tolerance)
  }
}
